import Head from "next/head";
import { NextPage } from "next";
import { signIn } from "next-auth/react";

type ProviderTypes = "github" | "google" | "discord";

const AUTH_PROVIDERS: ProviderTypes[] = ["github", "google", "discord"];
const NOT_IMPLEMENTED = ["google", "discord"];

const ProviderLogin = ({ provider }: { provider: ProviderTypes }) => {
  const providerImplemented = !NOT_IMPLEMENTED.includes(provider);
  return (
    <button
      disabled={!providerImplemented}
      onClick={() => signIn(provider)}
      className={`mt-2 rounded-md px-4 pb-2 transition-[padding] duration-150 ease-out ${
        providerImplemented && "hover:bg-red-500 hover:pt-2 hover:text-stone-50"
      } font-bold text-xl font-base capitalize ${
        !providerImplemented && "text-gray-400"
      }`}
    >
      {provider}
    </button>
  );
};

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>AppTrack - Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-start items-center">
        <h1 className="text-3xl pb-4">Let's get started! Sign in with:</h1>
        <nav className="mx-auto flex h-[36px] max-w-screen-sm items-start justify-center gap-1.5 text-xl">
          {AUTH_PROVIDERS.map((prov, idx) => (
            <ProviderLogin key={idx} provider={prov} />
          ))}
        </nav>
      </main>
    </>
  );
};

export default Login;
